version: '3'
name: mdevoldere-mariadb-standalone
volumes:
  db_data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./dev/myprojectdata:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"