name: mdevoldere-mariadb
volumes:
  db_mariadb:
services:
  db:
    image: mariadb:11.8.5
    container_name: mdevoldere-mariadb-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./dev/myprojectdata:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"