version: '3.8'
name: mdevoldere-mongodb-standalone 
volumes:
  mongodb_data:
services:
  mongodb:
    image: mongo:7.0-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db