version: "3.8"
name: myvuejs
services:
  vue:
    build: .
    ports:
      - 3000:3000
    volumes: # (probably delete this too)
      - ./:/app
    env_file:
      - ./.env
  nginx:
    image: nginx:1.15
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443