name: mdevoldere-symfony8
volumes:
  symfony8_mariadb: {}
services: 
  db:
    image: mariadb:11.8.5
    container_name: mdevoldere-symfony8-mariadb
    restart: unless-stopped
    ports: ['3306:3306']
    volumes:
      - symfony8_mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: db_symfony8
      MYSQL_USER: user 
      MYSQL_PASSWORD: secret

  web:
    # image: "php:8.4-apache"
    container_name: mdevoldere-symfony8-apache2
    build: 
      context: .
      dockerfile: apache.dockerfile
    restart: unless-stopped
    depends_on: ['db']
    ports: ['8000:80']
    links: ['db:db']
    volumes:
      - './src/:/var/www/html'
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DATABASE: db_test
      MYSQL_USER: user 
      MYSQL_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: mdevoldere-symfony8-phpmyadmin
    restart: unless-stopped
    depends_on: ['db']
    ports: ['1200:80']
    links: ['db:db']
    environment:
      - MYSQL_DB_HOST=db
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=secret
